/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopcagroupeapp;

import java.awt.Color;


/**
 *
 * @Vincentas Tarasevicius x23524449
 */
public class CompareMat extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CompareMat.class.getName());

    /**
     * Creates new form CompareMat
     */
    public CompareMat() {
        initComponents();
        getContentPane().setBackground(Color.decode("#6EA0B1"));
        compareButton.setBackground(Color.decode("#E5690B"));
        menuButton.setBackground(Color.decode("#E5690B"));
        materialsPanel.setBackground(Color.decode("#E5690B"));
        recycledConcreteCheckBox.setBackground(Color.decode("#E5690B"));
        recycledSteelCheckBox.setBackground(Color.decode("#E5690B"));
        recycledWoodCheckBox.setBackground(Color.decode("#E5690B"));
        concreteCheckBox.setBackground(Color.decode("#E5690B"));
        woodCheckBox.setBackground(Color.decode("#E5690B"));
        steelCheckBox.setBackground(Color.decode("#E5690B"));

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        compareLabel = new javax.swing.JLabel();
        materialsPanel = new javax.swing.JPanel();
        recycledConcreteCheckBox = new javax.swing.JCheckBox();
        concreteCheckBox = new javax.swing.JCheckBox();
        woodCheckBox = new javax.swing.JCheckBox();
        recycledWoodCheckBox = new javax.swing.JCheckBox();
        recycledSteelCheckBox = new javax.swing.JCheckBox();
        steelCheckBox = new javax.swing.JCheckBox();
        traditionalLabel = new javax.swing.JLabel();
        recycledLabel = new javax.swing.JLabel();
        compareButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        compareLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        compareLabel.setText("Compare Materials");

        recycledConcreteCheckBox.setText("Recycled Concrete");
        recycledConcreteCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recycledConcreteCheckBoxActionPerformed(evt);
            }
        });

        concreteCheckBox.setText("Concrete");

        woodCheckBox.setText("Wood");

        recycledWoodCheckBox.setText("Recycled Wood");

        recycledSteelCheckBox.setText("Recycled Steel");

        steelCheckBox.setText("Steel");
        steelCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                steelCheckBoxActionPerformed(evt);
            }
        });

        traditionalLabel.setText("Traditional Materials");

        recycledLabel.setText("Recycled Materials");

        javax.swing.GroupLayout materialsPanelLayout = new javax.swing.GroupLayout(materialsPanel);
        materialsPanel.setLayout(materialsPanelLayout);
        materialsPanelLayout.setHorizontalGroup(
            materialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(materialsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(materialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(traditionalLabel)
                    .addComponent(steelCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(woodCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(concreteCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addGroup(materialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recycledConcreteCheckBox)
                    .addComponent(recycledSteelCheckBox)
                    .addComponent(recycledWoodCheckBox)
                    .addComponent(recycledLabel))
                .addGap(8, 8, 8))
        );
        materialsPanelLayout.setVerticalGroup(
            materialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(materialsPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(materialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(traditionalLabel)
                    .addComponent(recycledLabel))
                .addGap(44, 44, 44)
                .addGroup(materialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recycledConcreteCheckBox)
                    .addComponent(concreteCheckBox))
                .addGap(77, 77, 77)
                .addGroup(materialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(steelCheckBox)
                    .addComponent(recycledSteelCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(materialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recycledWoodCheckBox)
                    .addComponent(woodCheckBox))
                .addGap(38, 38, 38))
        );

        compareButton.setText("Compare");
        compareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareButtonActionPerformed(evt);
            }
        });

        menuButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuButton.setText("Return to Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(menuButton)
                        .addGap(164, 164, 164))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(materialsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(compareLabel)
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(compareButton)
                        .addGap(209, 209, 209))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(compareLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(materialsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(compareButton)
                .addGap(26, 26, 26)
                .addComponent(menuButton)
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void steelCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_steelCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_steelCheckBoxActionPerformed

    private void recycledConcreteCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recycledConcreteCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recycledConcreteCheckBoxActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        InfrastructurePlanner mainMenu = new InfrastructurePlanner();
        mainMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuButtonActionPerformed

    private void compareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareButtonActionPerformed
        //making the mesage with a String
        String message = "Compare Materials";
        //check each of the materilas in the checkboxs and append the message
        if(concreteCheckBox.isSelected()){
            message += "Concrete: 0.15 kg CO2. ";   //regular concrete has more CO2
        }
        if(recycledConcreteCheckBox.isSelected()){
            message += " Recycled Concrete: 0.05 kg CO2. "; //  Recycled concrete has lower CO2
        }
        if(steelCheckBox.isSelected()){
            message += "Steel: 2.5 kg CO2. ";   // steel has more CO2
        }
        if(recycledSteelCheckBox.isSelected()){
            message += "Recycled Steel: 0.5 kg CO2. ";  //recycled steel has less CO2
        }
        if(woodCheckBox.isSelected()){
            message += "Wood: 0.05 kg CO2. ";   //egualr wood has more CO2
        }
        if(recycledWoodCheckBox.isSelected()){
            message += "Recycled Wood: 0.02 kg CO2. "; // recycled CO2 has less CO2
        }
        //to check if the person actauly ticked the box
        //if no boxes where selected it will still give you the same message
        if(message.equals("Compare Materials ")){
            // make user know to selcet the materilas like a message
            message = "Can you please select at least one or two materials to compare!";
        }
        //this actually prints the message 
        javax.swing.JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_compareButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CompareMat().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compareButton;
    private javax.swing.JLabel compareLabel;
    private javax.swing.JCheckBox concreteCheckBox;
    private javax.swing.JPanel materialsPanel;
    private javax.swing.JButton menuButton;
    private javax.swing.JCheckBox recycledConcreteCheckBox;
    private javax.swing.JLabel recycledLabel;
    private javax.swing.JCheckBox recycledSteelCheckBox;
    private javax.swing.JCheckBox recycledWoodCheckBox;
    private javax.swing.JCheckBox steelCheckBox;
    private javax.swing.JLabel traditionalLabel;
    private javax.swing.JCheckBox woodCheckBox;
    // End of variables declaration//GEN-END:variables
}
