/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopcagroupeapp;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @Vincentas Tarasevicius x23524449
 */
abstract class Cost{
    protected double amount;
    protected String costType;
    
    public Cost(double amount, String costType){
        this.amount = amount;
        this.costType = costType;
    }
    public abstract double calculateCost();
    public abstract String getCost();
    
    public double getAmount(){
        return amount;
    }
    public String getCostType(){
        return costType;
    }
}
    
class MaterialCost extends Cost{
    public MaterialCost(double amount){
        super(amount, "Materials");
        }
    
    @Override
    public double calculateCost(){
        return amount;
    }
    @Override
    public String getCost(){
        return "Materials: " + amount;
    }
}

class LabourCost extends Cost{
    public LabourCost(double amount){
        super(amount, "Labour");
    }
    @Override
    public double calculateCost(){
        return amount;
    }
    @Override
    public String getCost(){
        return "Labour: " + amount;
    }
}
public class CostCal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CostCal.class.getName());

    /**
     * Creates new form CostCal
     */
    public CostCal() {
        initComponents();
        getContentPane().setBackground(Color.decode("#6EA0B1"));
        calculateButton.setBackground(Color.decode("#E5690B"));
        menuButton.setBackground(Color.decode("#E5690B"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        materialField = new javax.swing.JLabel();
        labourField = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        labourTextField = new javax.swing.JTextField();
        materialTextField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setText("Cost Calculator");

        materialField.setText("Material Cost:");
        materialField.setPreferredSize(new java.awt.Dimension(150, 30));

        labourField.setText("Labour Cost:");

        totalLabel.setText("Total: 0.00");

        labourTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labourTextFieldActionPerformed(evt);
            }
        });

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        menuButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuButton.setText("Back to Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labourField)
                    .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(materialField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuButton)
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materialField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labourField)
                    .addComponent(labourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(menuButton)
                .addGap(52, 52, 52))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labourTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labourTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labourTextFieldActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        InfrastructurePlanner mainMenu = new InfrastructurePlanner();
        mainMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuButtonActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        try{
            double material = Double.parseDouble(materialTextField.getText());
            double labour = Double.parseDouble(labourTextField.getText());
            
            Cost materialCost = new MaterialCost(material);
            Cost labourCost = new LabourCost(labour);
            
            double materialTotal = materialCost.calculateCost();
            double labourTotal = labourCost.calculateCost();
            double total = materialTotal + labourTotal;
            
            totalLabel.setText("Total: " + total);
            
            String details = "Final Cost\n"
                    +
                    materialCost.getCost() + "\n"
                    +
                    labourCost.getCost() + "\n"
                    +
                    "Total " + total;
            
            JOptionPane.showMessageDialog(this, details);
        }catch (Exception e){
            totalLabel.setText("Total: Invalid input");
        }
    }//GEN-LAST:event_calculateButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CostCal().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel labourField;
    private javax.swing.JTextField labourTextField;
    private javax.swing.JLabel materialField;
    private javax.swing.JTextField materialTextField;
    private javax.swing.JButton menuButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}