/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopcagroupeapp;

import java.awt.Color;


/**
 *
 * @Vincentas Tarasevicius x23524449
 */
public class EnvironmentCal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EnvironmentCal.class.getName());

    /**
     * Creates new form EnvironmentCal
     */
    public EnvironmentCal() {
        initComponents();
        getContentPane().setBackground(Color.decode("#6EA0B1"));
        menuButton.setBackground(Color.decode("#E5690B"));
        calculateButton.setBackground(Color.decode("#E5690B"));
        projectComboBox.setBackground(Color.decode("#E5690B"));
        materialsPanel.setBackground(Color.decode("#E5690B"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calLabel = new javax.swing.JLabel();
        projectLabel = new javax.swing.JLabel();
        projectComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        materialsPanel = new javax.swing.JPanel();
        concreteLabel = new javax.swing.JLabel();
        steelLabel = new javax.swing.JLabel();
        woodLabel = new javax.swing.JLabel();
        recycledConcreteLabel = new javax.swing.JLabel();
        recycledSteelLabel = new javax.swing.JLabel();
        recycledWoodLabel = new javax.swing.JLabel();
        concreteTextField = new javax.swing.JTextField();
        steelTextField = new javax.swing.JTextField();
        woodTextField = new javax.swing.JTextField();
        recycledSteelTextField = new javax.swing.JTextField();
        recycledConcreteTextField = new javax.swing.JTextField();
        recycledWoodTextField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        menuButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        calLabel.setText("Environmental Calculator");

        projectLabel.setText("Project:");

        projectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large" }));
        projectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Materials Used:");

        concreteLabel.setText("Concrete");

        steelLabel.setText("Steel");

        woodLabel.setText("Wood");

        recycledConcreteLabel.setText("Recycled Concrete");

        recycledSteelLabel.setText("Recycled Steel");

        recycledWoodLabel.setText("Recycled Wood");

        concreteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concreteTextFieldActionPerformed(evt);
            }
        });

        steelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                steelTextFieldActionPerformed(evt);
            }
        });

        woodTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                woodTextFieldActionPerformed(evt);
            }
        });

        recycledSteelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recycledSteelTextFieldActionPerformed(evt);
            }
        });

        recycledConcreteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recycledConcreteTextFieldActionPerformed(evt);
            }
        });

        recycledWoodTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recycledWoodTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout materialsPanelLayout = new javax.swing.GroupLayout(materialsPanel);
        materialsPanel.setLayout(materialsPanelLayout);
        materialsPanelLayout.setHorizontalGroup(
            materialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(materialsPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(materialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(materialsPanelLayout.createSequentialGroup()
                        .addGroup(materialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(materialsPanelLayout.createSequentialGroup()
                                .addComponent(steelLabel)
                                .addGap(27, 27, 27)
                                .addComponent(steelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(materialsPanelLayout.createSequentialGroup()
                                .addComponent(concreteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(concreteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addGroup(materialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, materialsPanelLayout.createSequentialGroup()
                                .addComponent(recycledConcreteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recycledConcreteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(materialsPanelLayout.createSequentialGroup()
                                .addComponent(recycledSteelLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(recycledSteelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(materialsPanelLayout.createSequentialGroup()
                        .addComponent(woodLabel)
                        .addGap(18, 18, 18)
                        .addComponent(woodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(recycledWoodLabel)
                        .addGap(18, 18, 18)
                        .addComponent(recycledWoodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        materialsPanelLayout.setVerticalGroup(
            materialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(materialsPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(materialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(concreteLabel)
                    .addComponent(recycledConcreteLabel)
                    .addComponent(concreteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recycledConcreteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(materialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(steelLabel)
                    .addComponent(steelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recycledSteelLabel)
                    .addComponent(recycledSteelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(materialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(woodLabel)
                    .addComponent(woodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recycledWoodLabel)
                    .addComponent(recycledWoodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        calculateButton.setText("Calculate Impact");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        menuButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuButton.setText("Return to Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calLabel)
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(materialsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(projectLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(projectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(calculateButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(menuButton)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(calLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(materialsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calculateButton)
                .addGap(30, 30, 30)
                .addComponent(menuButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void concreteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concreteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_concreteTextFieldActionPerformed

    private void steelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_steelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_steelTextFieldActionPerformed

    private void woodTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_woodTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_woodTextFieldActionPerformed

    private void recycledWoodTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recycledWoodTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recycledWoodTextFieldActionPerformed

    private void recycledSteelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recycledSteelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recycledSteelTextFieldActionPerformed

    private void recycledConcreteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recycledConcreteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recycledConcreteTextFieldActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        InfrastructurePlanner mainMenu = new InfrastructurePlanner();
        mainMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuButtonActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
    try{
        //gets the user inputs
        String projectSize = (String) projectComboBox.getSelectedItem();
        double concrete = Double.parseDouble(concreteTextField.getText());
        double steel = Double.parseDouble(steelTextField.getText());
        double wood = Double.parseDouble(woodTextField.getText());
        double recycledConcrete = Double.parseDouble(recycledConcreteTextField.getText());
        double recycledSteel = Double.parseDouble(recycledSteelTextField.getText());
        double recycledWood = Double.parseDouble(recycledWoodTextField.getText());
        // gets the carbon footprint for each material
        double concreteImpact = 0.15;
        double steelImpact = 2.5;
        double woodImpact = 0.05;
        double recycledConcreteImpact = 0.05;
        double recycledSteelImpact = 0.5;
        double recycledWoodImpact = 0.02;
        //calculates CO2 for each material 
        double totalConcreteCO2 = (concrete * concreteImpact) + (recycledConcrete * recycledConcreteImpact);
        double totalSteelCO2 = (steel * steelImpact) + (recycledSteel * recycledSteelImpact);
        double totalWoodCO2 = (wood * woodImpact) + (recycledWood * recycledWoodImpact);
        //calculates the CO2 before the size multiplyer
        double baseCO2 = totalConcreteCO2 + totalSteelCO2 + totalWoodCO2;
        //applies the project size mulitplier
        double projectMultiplier = getProjectMultiplier(projectSize);
        double totalCO2 = baseCO2 * projectMultiplier;
        
        double totalMaterials = concrete + steel + wood + recycledConcrete + recycledSteel + recycledWood;
        double totalRecycled = recycledConcrete + recycledSteel + recycledWood;
        double recycledPercentage = (totalRecycled/totalMaterials) * 100;
        // this shows the reults
        //using a string format to display a message
        String results = String.format("Project: %s Total CO2: %.2f kg Recycled: %.1f%%", projectSize, totalCO2, recycledPercentage);
        javax.swing.JOptionPane.showMessageDialog(this, results);
        }catch(NumberFormatException e){
            // this is when the user enters text instead of numbers
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid numbers in all fields");
        }
    }
    // this gets all of the project sizes from the list
    private double getProjectMultiplier(String projectSize){
        if(projectSize.equals("Small")){
            return 1.0;
        }else if(projectSize.equals("Medium")){
            return 1.5;
        }else if(projectSize.equals("Large")){
            return 2.5;
        }else{
            return 1.0;
        }
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void projectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EnvironmentCal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calLabel;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel concreteLabel;
    private javax.swing.JTextField concreteTextField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel materialsPanel;
    private javax.swing.JToggleButton menuButton;
    private javax.swing.JComboBox<String> projectComboBox;
    private javax.swing.JLabel projectLabel;
    private javax.swing.JLabel recycledConcreteLabel;
    private javax.swing.JTextField recycledConcreteTextField;
    private javax.swing.JLabel recycledSteelLabel;
    private javax.swing.JTextField recycledSteelTextField;
    private javax.swing.JLabel recycledWoodLabel;
    private javax.swing.JTextField recycledWoodTextField;
    private javax.swing.JLabel steelLabel;
    private javax.swing.JTextField steelTextField;
    private javax.swing.JLabel woodLabel;
    private javax.swing.JTextField woodTextField;
    // End of variables declaration//GEN-END:variables
}
