/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopcagroupeapp;

/**
 *
 * @author taara
 */
public class EnvironmentCal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EnvironmentCal.class.getName());

    /**
     * Creates new form EnvironmentCal
     */
    public EnvironmentCal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calLabel = new javax.swing.JLabel();
        projectLabel = new javax.swing.JLabel();
        projectComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        materilasPanel = new javax.swing.JPanel();
        concreteLabel = new javax.swing.JLabel();
        steelLabel = new javax.swing.JLabel();
        woodLabel = new javax.swing.JLabel();
        recycledConcreteLabel = new javax.swing.JLabel();
        recycledSteelLabel = new javax.swing.JLabel();
        recycledWoodLabel = new javax.swing.JLabel();
        concreteTextField = new javax.swing.JTextField();
        steelTextField = new javax.swing.JTextField();
        woodTextField = new javax.swing.JTextField();
        recycledSteelTextField = new javax.swing.JTextField();
        recycledConcreteTextField = new javax.swing.JTextField();
        recycledWoodTextField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        resultsLabel = new javax.swing.JLabel();
        textPanel = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        calLabel.setText("Environmental Calculator");

        projectLabel.setText("Project:");

        projectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large" }));

        jLabel3.setText("Materials Used:");

        concreteLabel.setText("Concrete");

        steelLabel.setText("Steel");

        woodLabel.setText("Wood");

        recycledConcreteLabel.setText("Recycled Concrete");

        recycledSteelLabel.setText("Recycled Steel");

        recycledWoodLabel.setText("Recycled Wood");

        concreteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concreteTextFieldActionPerformed(evt);
            }
        });

        steelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                steelTextFieldActionPerformed(evt);
            }
        });

        woodTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                woodTextFieldActionPerformed(evt);
            }
        });

        recycledSteelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recycledSteelTextFieldActionPerformed(evt);
            }
        });

        recycledConcreteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recycledConcreteTextFieldActionPerformed(evt);
            }
        });

        recycledWoodTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recycledWoodTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout materilasPanelLayout = new javax.swing.GroupLayout(materilasPanel);
        materilasPanel.setLayout(materilasPanelLayout);
        materilasPanelLayout.setHorizontalGroup(
            materilasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, materilasPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(materilasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(materilasPanelLayout.createSequentialGroup()
                        .addComponent(steelLabel)
                        .addGap(27, 27, 27)
                        .addComponent(steelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(materilasPanelLayout.createSequentialGroup()
                        .addComponent(woodLabel)
                        .addGap(20, 20, 20)
                        .addComponent(woodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(materilasPanelLayout.createSequentialGroup()
                        .addComponent(concreteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(concreteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(materilasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(materilasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(materilasPanelLayout.createSequentialGroup()
                            .addComponent(recycledSteelLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(recycledSteelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(materilasPanelLayout.createSequentialGroup()
                            .addComponent(recycledConcreteLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(recycledConcreteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(materilasPanelLayout.createSequentialGroup()
                        .addComponent(recycledWoodLabel)
                        .addGap(21, 21, 21)
                        .addComponent(recycledWoodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        materilasPanelLayout.setVerticalGroup(
            materilasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(materilasPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(materilasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(concreteLabel)
                    .addComponent(recycledConcreteLabel)
                    .addComponent(concreteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recycledConcreteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(materilasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(steelLabel)
                    .addComponent(recycledSteelLabel)
                    .addComponent(recycledSteelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(steelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(materilasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(woodLabel)
                    .addComponent(recycledWoodLabel)
                    .addComponent(woodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recycledWoodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        calculateButton.setText("Calculate Impact");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        resultsLabel.setText("Results:");

        javax.swing.GroupLayout textPanelLayout = new javax.swing.GroupLayout(textPanel);
        textPanel.setLayout(textPanelLayout);
        textPanelLayout.setHorizontalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        textPanelLayout.setVerticalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton1.setText("Return to Menu");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(materilasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(projectLabel)
                                .addGap(18, 18, 18)
                                .addComponent(projectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(calculateButton))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(resultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calLabel)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calLabel)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(materilasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calculateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void concreteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concreteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_concreteTextFieldActionPerformed

    private void steelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_steelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_steelTextFieldActionPerformed

    private void woodTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_woodTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_woodTextFieldActionPerformed

    private void recycledWoodTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recycledWoodTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recycledWoodTextFieldActionPerformed

    private void recycledSteelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recycledSteelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recycledSteelTextFieldActionPerformed

    private void recycledConcreteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recycledConcreteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recycledConcreteTextFieldActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        InfastructurePlanner mainMenu = new InfastructurePlanner();
        mainMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calculateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EnvironmentCal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calLabel;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel concreteLabel;
    private javax.swing.JTextField concreteTextField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel materilasPanel;
    private javax.swing.JComboBox<String> projectComboBox;
    private javax.swing.JLabel projectLabel;
    private javax.swing.JLabel recycledConcreteLabel;
    private javax.swing.JTextField recycledConcreteTextField;
    private javax.swing.JLabel recycledSteelLabel;
    private javax.swing.JTextField recycledSteelTextField;
    private javax.swing.JLabel recycledWoodLabel;
    private javax.swing.JTextField recycledWoodTextField;
    private javax.swing.JLabel resultsLabel;
    private javax.swing.JLabel steelLabel;
    private javax.swing.JTextField steelTextField;
    private javax.swing.JPanel textPanel;
    private javax.swing.JLabel woodLabel;
    private javax.swing.JTextField woodTextField;
    // End of variables declaration//GEN-END:variables
}
