/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopcagroupeapp;

/**
 *
 * @Vincentas Tarasevicius x23524449
 */
public class InfrastructurePlanner extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InfrastructurePlanner.class.getName());

    /**
     * Creates new form InfastructurePlanner
     */
    public InfrastructurePlanner() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        costCalButton = new javax.swing.JButton();
        envCalButton = new javax.swing.JButton();
        mainButton = new javax.swing.JButton();
        compMatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("InfastructurePlanner");

        costCalButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        costCalButton.setText("Cost Calculator");
        costCalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costCalButtonActionPerformed(evt);
            }
        });

        envCalButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        envCalButton.setText("Enironment Calculator");
        envCalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envCalButtonActionPerformed(evt);
            }
        });

        mainButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mainButton.setText("Main Menu");
        mainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainButtonActionPerformed(evt);
            }
        });

        compMatButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        compMatButton.setText("Compare Materials");
        compMatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compMatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(costCalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(envCalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(compMatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(136, 136, 136))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {compMatButton, costCalButton, envCalButton, jLabel1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(costCalButton)
                .addGap(71, 71, 71)
                .addComponent(envCalButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(compMatButton)
                .addGap(75, 75, 75)
                .addComponent(mainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {compMatButton, costCalButton, envCalButton, jLabel1, mainButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void costCalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costCalButtonActionPerformed
        CostCal costCal = new CostCal();
        costCal.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_costCalButtonActionPerformed

    private void envCalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envCalButtonActionPerformed
        EnvironmentCal envCal = new EnvironmentCal();
        envCal.setVisible(true);
        dispose();
    }//GEN-LAST:event_envCalButtonActionPerformed

    private void mainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainButtonActionPerformed
        MainGUI main = new MainGUI();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_mainButtonActionPerformed

    private void compMatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compMatButtonActionPerformed
        CompareMat compareMat = new CompareMat();
        compareMat.setVisible(true);
        dispose();
    }//GEN-LAST:event_compMatButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InfrastructurePlanner().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compMatButton;
    private javax.swing.JButton costCalButton;
    private javax.swing.JButton envCalButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mainButton;
    // End of variables declaration//GEN-END:variables
}
